(()=>{'use strict';
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const state={mode:'core',history:[],attachment:null};
const toast=m=>{const e=$('#toast');e.textContent=m;e.classList.add('show');clearTimeout(toast.t);toast.t=setTimeout(()=>e.classList.remove('show'),2600)};
// One lightweight visual field behind the whole app. Scroll changes the field's depth; it pauses when hidden.
const canvas=$('#field'),ctx=canvas.getContext('2d',{alpha:true}),reduced=matchMedia('(prefers-reduced-motion: reduce)'),mobile=matchMedia('(max-width: 700px)');let W=0,H=0,dpr=1,particles=[],raf=0,mouse={x:.5,y:.5},scroll=0;
function resize(){W=innerWidth;H=innerHeight;dpr=Math.min(devicePixelRatio||1,2);canvas.width=W*dpr;canvas.height=H*dpr;canvas.style.width=W+'px';canvas.style.height=H+'px';ctx.setTransform(dpr,0,0,dpr,0,0);const n=reduced.matches?0:(mobile.matches?24:Math.min(58,Math.floor(W*H/26000)));particles=Array.from({length:n},()=>({x:Math.random()*W,y:Math.random()*H,vx:(Math.random()-.5)*.1,vy:(Math.random()-.5)*.1,z:.3+Math.random()*.7,p:Math.random()*6.28}))}
function draw(){ctx.clearRect(0,0,W,H);if(!particles.length)return;const drift=scroll*.00035;for(const p of particles){p.p+=.004;p.x+=p.vx+(mouse.x-.5)*.025*p.z;p.y+=p.vy+(mouse.y-.5)*.018*p.z+Math.sin(p.p)*.015;p.x+=drift*W*p.z;if(p.x<0)p.x=W;if(p.x>W)p.x=0;if(p.y<0)p.y=H;if(p.y>H)p.y=0;ctx.beginPath();ctx.fillStyle=`rgba(190,140,255,${.1+.18*p.z})`;ctx.arc(p.x,p.y,1.05*p.z,0,Math.PI*2);ctx.fill()}for(let i=0;i<particles.length;i++)for(let j=i+1;j<particles.length;j++){const a=particles[i],b=particles[j],d=Math.hypot(a.x-b.x,a.y-b.y);if(d<95){ctx.strokeStyle=`rgba(120,90,170,${.045*(1-d/95)})`;ctx.beginPath();ctx.moveTo(a.x,a.y);ctx.lineTo(b.x,b.y);ctx.stroke()}}raf=requestAnimationFrame(draw)}
addEventListener('resize',resize,{passive:true});addEventListener('pointermove',e=>{mouse.x=e.clientX/W;mouse.y=e.clientY/H},{passive:true});addEventListener('scroll',()=>scroll=scrollY,{passive:true});document.addEventListener('visibilitychange',()=>{if(document.hidden)cancelAnimationFrame(raf);else if(!reduced.matches)raf=requestAnimationFrame(draw)});resize();if(!reduced.matches)raf=requestAnimationFrame(draw);
const menu=$('.menu-toggle'),nav=$('#nav');menu.addEventListener('click',()=>{const open=menu.getAttribute('aria-expanded')==='true';menu.setAttribute('aria-expanded',String(!open));nav.style.display=open?'':'flex'});$$('.nav a').forEach(a=>a.addEventListener('click',()=>{menu.setAttribute('aria-expanded','false');nav.style.display=''}));
const observer=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting)e.target.classList.add('visible')}),{threshold:.08});$$('.reveal').forEach(e=>observer.observe(e));
const examples={core:'Ask Dost anything...',developer:'Help me debug this JavaScript error.',cyber:'Explain how to detect suspicious network behavior defensively.',study:'Create a 14-day networking study plan.',career:'Analyze my CV and suggest suitable roles.',builder:'Build a responsive website from this brief.'};
function setMode(mode){state.mode=mode;const label={core:'GENERAL',developer:'DEVELOPER',cyber:'CYBERSECURITY',study:'STUDY',career:'CAREER'}[mode]||'GENERAL';$('#activeModeLabel').textContent=label;$$('.mode-pill').forEach(b=>b.classList.toggle('active',b.dataset.mode===mode));$('#prompt').placeholder=examples[mode]||examples.core}
$$('.mode-pill').forEach(b=>b.addEventListener('click',()=>setMode(b.dataset.mode)));$$('[data-jump]').forEach(b=>b.addEventListener('click',()=>{setMode(b.dataset.jump);$('#assistant').scrollIntoView({behavior:reduced.matches?'auto':'smooth'})}));
const prompt=$('#prompt');prompt.addEventListener('input',()=>$('#charCount').textContent=`${prompt.value.length} / 16000`);$$('.suggestions button').forEach(b=>b.addEventListener('click',()=>{prompt.value=b.dataset.example;prompt.dispatchEvent(new Event('input'));prompt.focus()}));
function setBusy(btn,busy,label){btn.disabled=busy;if(busy)btn.textContent=label;else btn.textContent=btn.id==='generateProject'?'Generate Project ✦':'Send ↗'}
async function postJSON(path,body){const r=await fetch(path,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(body)});let d={};try{d=await r.json()}catch{}if(!r.ok||d.success===false)throw new Error(d.error||`Request failed (${r.status})`);return d}
function escapeHtml(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}function safeUrl(u){try{const x=new URL(u,location.origin);return ['http:','https:'].includes(x.protocol)?x.href:'#'}catch{return '#'}}
async function loadScript(src){return new Promise((resolve,reject)=>{const s=document.createElement('script');s.src=src;s.onload=resolve;s.onerror=reject;document.head.appendChild(s)})}
async function readAttachment(f){
  state.attachment=f;
  if(['text/plain','text/markdown','application/json','text/csv'].includes(f.type)||/\.(txt|md|json|csv)$/i.test(f.name)) return (await f.text()).slice(0,30000);
  if(/\.pdf$/i.test(f.name)){
    try{
      if(!window.pdfjsLib){const m=await import('https://cdnjs.cloudflare.com/ajax/libs/pdf.js/4.4.168/pdf.min.mjs');window.pdfjsLib=m;}
      if(window.pdfjsLib.GlobalWorkerOptions) window.pdfjsLib.GlobalWorkerOptions.workerSrc='https://cdnjs.cloudflare.com/ajax/libs/pdf.js/4.4.168/pdf.worker.min.mjs';
      const pdf=await window.pdfjsLib.getDocument({data:await f.arrayBuffer()}).promise;let out='';
      for(let i=1;i<=Math.min(pdf.numPages,8);i++){const page=await pdf.getPage(i);const tc=await page.getTextContent();out+=tc.items.map(x=>x.str).join(' ')+'\n';}
      return out.slice(0,30000);
    }catch{}
  }
  if(/\.docx$/i.test(f.name)){
    try{if(!window.mammoth) await loadScript('https://cdnjs.cloudflare.com/ajax/libs/mammoth/1.8.0/mammoth.browser.min.js');const r=await window.mammoth.extractRawText({arrayBuffer:await f.arrayBuffer()});return (r.value||'').slice(0,30000)}catch{}
  }
  return '';
}
$('#chatFile').addEventListener('change',async e=>{const f=e.target.files[0];if(!f)return;$('#attachmentName').textContent=f.name;try{const text=await readAttachment(f);state.attachment={name:f.name,text};toast(text?`${f.name} attached and read`:`${f.name} attached`)}catch{toast(`${f.name} attached`)}});
$('#sendChat').addEventListener('click',async()=>{const text=prompt.value.trim();if(!text)return toast('Write a prompt first.');const btn=$('#sendChat');$('#connectionStatus').textContent='WORKING';setBusy(btn,true,'Thinking…');$('#response').innerHTML='<div class="response-empty"><span class="response-icon">D</span><div><b>Dost is thinking…</b><p>Working through your request.</p></div></div>';try{const userContent=state.attachment?.text?`${text}\n\n[Attached file: ${state.attachment.name}]\n${state.attachment.text}`:text;state.history.push({role:'user',content:userContent});const data=await postJSON('/api/chat',{prompt:text,mode:state.mode,history:state.history.slice(-10),attachment:state.attachment||null});state.history.push({role:'assistant',content:data.answer||''});$('#response').innerHTML=`<div><b>DOST</b><p style="white-space:pre-wrap;color:#ddd;margin-top:10px">${escapeHtml(data.answer||'No answer returned.')}</p></div>`;$('#connectionStatus').textContent='ONLINE';state.attachment=null;$('#attachmentName').textContent=''}catch(e){state.history.pop();$('#response').innerHTML=`<div><b>Connection not available yet.</b><p style="white-space:pre-wrap;color:#aaa">${escapeHtml(e.message)}<br><br>The interface is ready. Configure the Worker AI provider to enable live answers.</p></div>`;$('#connectionStatus').textContent='UI READY';toast('AI connection unavailable')}finally{setBusy(btn,false)}});
let cvFile=null;$('#cvFile').addEventListener('change',e=>{cvFile=e.target.files[0]||null;$('#cvLabel').textContent=cvFile?cvFile.name:'Drop CV or choose a file'});
$('#findJobs').addEventListener('click',async()=>{if(!cvFile)return toast('Choose a CV first.');const country=$('#country').value,focus=$('#roleFocus').value.trim(),out=$('#jobResults');out.innerHTML='<div class="job-empty"><span>◎</span><b>Dost is scanning connected job sources…</b><p>Extracting skills, building a search query and ranking matches.</p></div>';try{const resumeText=await readAttachment(cvFile);if(!resumeText&&!focus)throw new Error('For this browser, add a role/keyword if the CV text cannot be extracted.');const data=await postJSON('/api/jobs',{country,role:focus,resumeText,fileName:cvFile.name});const jobs=data.jobs||[];const sourceLine=(data.sources||[]).join(' · ');out.innerHTML=jobs.length?`<div class="source-note"><b>Found across</b><span>${escapeHtml(sourceLine||'connected sources')}</span></div>`+jobs.map(j=>`<article class="job-card"><b>${escapeHtml(j.title||'Role')}</b><span>${escapeHtml(j.company||'Company')} · ${escapeHtml(j.location||country)}</span><div class="job-meta">${j.source?`<i>${escapeHtml(j.source)}</i>`:''}${j.match?`<i>${escapeHtml(j.match)}% fit</i>`:''}${j.remote?'<i>Remote</i>':''}</div>${j.url?`<a href="${safeUrl(j.url)}" target="_blank" rel="noopener noreferrer">View & apply →</a>`:''}</article>`).join('')+(data.boardLinks?.length?`<div class="source-note"><b>More boards</b>${data.boardLinks.map(x=>`<a href="${safeUrl(x.url)}" target="_blank" rel="noopener noreferrer">${escapeHtml(x.name)}</a>`).join('')}</div>`:''):`<div class="job-empty"><span>◎</span><b>No connected matches yet.</b><p>${escapeHtml(data.message||'Try broader keywords or enable more job provider keys.')}</p></div>`}catch(e){out.innerHTML=`<div class="job-empty"><span>!</span><b>Job search could not complete.</b><p>${escapeHtml(e.message)}</p></div>`;toast('Job search unavailable')}});
const buildPrompt=$('#buildPrompt');buildPrompt.addEventListener('input',()=>$('#buildCount').textContent=`${buildPrompt.value.length} / 16000`);let latestFiles=[];
function renderFiles(files){$('#fileList').innerHTML=files.map(f=>`<span style="display:inline-block;margin:3px;padding:4px 7px;border:1px solid rgba(255,255,255,.07);border-radius:6px">${escapeHtml(f.path)}</span>`).join('')}
function renderPreview(files){const index=files.find(f=>f.path.toLowerCase()==='index.html')||files.find(f=>/\.html$/i.test(f.path));if(!index){$('#preview').srcdoc='<p>No index.html generated.</p>';return}let html=index.content;const css=files.filter(f=>/\.css$/i.test(f.path)).map(f=>f.content).join('\n');const js=files.filter(f=>/\.js$/i.test(f.path)).map(f=>f.content).join('\n');if(css&&!/<style/i.test(html))html=html.replace('</head>',`<style>${css}</style></head>`);if(js&&!/<script/i.test(html))html=html.replace('</body>',`<script>${js.replace(/<\/script>/gi,'<\\/script>')}<\/script></body>`);$('#preview').srcdoc=html}
$('#generateProject').addEventListener('click',async()=>{const text=buildPrompt.value.trim();if(!text)return toast('Write a project brief first.');const btn=$('#generateProject');setBusy(btn,true,'Generating…');try{const d=await postJSON('/api/generate',{prompt:text,type:'website'});latestFiles=d.files||[];renderFiles(latestFiles);renderPreview(latestFiles);$('#downloadZip').disabled=!latestFiles.length;$('#openPreview').disabled=!latestFiles.length;toast(`${latestFiles.length} files generated`)}catch(e){$('#fileList').textContent=e.message;toast('Project generation failed')}finally{setBusy(btn,false)}});
$('#openPreview').addEventListener('click',()=>{const w=open();if(w){w.document.write($('#preview').srcdoc||'<p>No preview</p>');w.document.close()}});$('#downloadZip').addEventListener('click',async()=>{if(!latestFiles.length)return;if(!window.JSZip)return toast('ZIP library still loading');const z=new JSZip();latestFiles.forEach(f=>z.file(f.path,f.content));const blob=await z.generateAsync({type:'blob'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='dost-generated-project.zip';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)});
})();
