const JSON_HEADERS={"content-type":"application/json; charset=utf-8","cache-control":"no-store"};
const MAX_PROMPT=16000, MAX_HISTORY=10;
function json(data,status=200){return new Response(JSON.stringify(data),{status,headers:{...JSON_HEADERS,"access-control-allow-origin":"*","access-control-allow-headers":"Content-Type","access-control-allow-methods":"GET,POST,OPTIONS"}})}
function clean(s,max=MAX_PROMPT){return typeof s==='string'?s.trim().slice(0,max):''}
function modeInstruction(mode){return ({developer:'Act as a senior software engineer. Diagnose root causes, propose safe fixes, tests, architecture and tradeoffs.',cyber:'Act as a defensive cybersecurity tutor. Focus on detection, hardening, secure architecture and safe labs. Refuse malware, credential theft, evasion, persistence and destructive instructions.',study:'Act as a patient study mentor. Explain simply, use examples, practice questions, spaced revision and a realistic plan.',career:'Act as a practical career coach. Map skills to roles, identify gaps and produce actionable next steps.',core:'Act as a general high-quality AI assistant. Be accurate, clear, honest about uncertainty and practical.'}[mode]||'Act as a helpful general AI assistant.')}
async function callOpenRouter(env,messages,{jsonMode=false}={}){if(!env.OPENROUTER_API_KEY)return null;const model=env.OPENROUTER_MODEL||'openai/gpt-oss-120b';const body={model,messages,temperature:.2,max_tokens:jsonMode?14000:3000};if(jsonMode)body.response_format={type:'json_object'};const r=await fetch('https://openrouter.ai/api/v1/chat/completions',{method:'POST',headers:{'content-type':'application/json','authorization':`Bearer ${env.OPENROUTER_API_KEY}`,'http-referer':env.PUBLIC_APP_URL||'https://dost-ai.local','x-title':'Dost AI'},body:JSON.stringify(body)});if(!r.ok)throw new Error(`AI provider error (${r.status})`);const d=await r.json();return d.choices?.[0]?.message?.content||''}
async function callWorkersAI(env,messages){if(!env.AI?.run)return null;const model=env.WORKERS_AI_MODEL||'@cf/meta/llama-3.1-8b-instruct-fast';const r=await env.AI.run(model,{messages,max_tokens:2400});return r?.response||''}
async function aiText(env,messages,opts={}){const a=await callOpenRouter(env,messages,opts);if(a)return {answer:a,provider:'OpenRouter'};const w=await callWorkersAI(env,messages);if(w)return {answer:w,provider:'Workers AI'};throw new Error('No AI provider is configured. Add OPENROUTER_API_KEY or a Workers AI binding.')}
async function chat(req,env){const b=await req.json();const prompt=clean(b.prompt);const mode=clean(b.mode,30)||'core';const history=Array.isArray(b.history)?b.history.slice(-MAX_HISTORY).filter(x=>x&&['user','assistant'].includes(x.role)&&typeof x.content==='string').map(x=>({role:x.role,content:x.content.slice(0,12000)})):[];const attachment=b.attachment?.text?`\nAttached document (${clean(b.attachment.name,120)}):\n${clean(b.attachment.text,30000)}`:'';if(!prompt)return json({success:false,error:'Prompt is required.'},400);const system=`You are Dost AI, a general-purpose assistant for developers, cybersecurity learners, students and career builders. ${modeInstruction(mode)} Never claim live browsing or actions unless a connected tool actually performed them. For job-search requests, use the dedicated job endpoint for listings. ${attachment?'Use the attached document as context when relevant.':''}`;try{const msgs=[{role:'system',content:system},...history,{role:'user',content:prompt+attachment}];const r=await aiText(env,msgs);return json({success:true,answer:r.answer,provider:r.provider,mode})}catch(e){return json({success:false,error:e.message},503)}}
function extractJson(text){try{return JSON.parse(text)}catch{const m=text.match(/\{[\s\S]*\}/);if(m){try{return JSON.parse(m[0])}catch{}}return null}}
async function generate(req,env){const b=await req.json();const prompt=clean(b.prompt);if(!prompt)return json({success:false,error:'Project brief is required.'},400);const system='Generate a small production-minded static web project. Return ONLY JSON: {"name":"kebab-name","files":[{"path":"index.html","content":"..."},{"path":"style.css","content":"..."},{"path":"script.js","content":"..."}]}. Keep it responsive, accessible, dependency-light and safe. Never include API keys or secrets.';try{const r=await aiText(env,[{role:'system',content:system},{role:'user',content:prompt}],{jsonMode:true});const obj=extractJson(r.answer);if(!obj||!Array.isArray(obj.files))throw new Error('AI returned an invalid project structure.');const files=obj.files.filter(f=>f&&typeof f.path==='string'&&typeof f.content==='string').slice(0,40).map(f=>({path:f.path.replace(/^\/+/,''),content:f.content.slice(0,120000)}));return json({success:true,name:obj.name||'dost-project',files,provider:r.provider})}catch(e){return json({success:false,error:e.message},503)}}
function countryCode(c){return ({PK:'pk',IN:'in',AE:'ae',SA:'sa',GB:'gb',DE:'de',CA:'ca',AU:'au',US:'us',NL:'nl',remote:null})[c]??null}
function normJob(j,source){return {title:j.title||j.position||j.name||'Role',company:j.company?.display_name||j.company_name||j.company||j.employer_name||'',location:j.location?.display_name||j.location||j.candidate_required_location||j.region||'',description:(j.description||j.snippet||'').replace(/<[^>]+>/g,'').slice(0,300),url:j.redirect_url||j.url||j.job_url||j.apply_url||'',source,remote:/remote|worldwide/i.test(`${j.location?.display_name||''} ${j.candidate_required_location||''} ${j.title||''}`)}}
async function adzuna(env,country,q){if(!env.ADZUNA_APP_ID||!env.ADZUNA_APP_KEY)return [];const cc=countryCode(country);if(!cc)return [];const u=new URL(`https://api.adzuna.com/v1/api/jobs/${cc}/search/1`);u.searchParams.set('app_id',env.ADZUNA_APP_ID);u.searchParams.set('app_key',env.ADZUNA_APP_KEY);u.searchParams.set('what',q);u.searchParams.set('results_per_page','12');u.searchParams.set('content-type','application/json');const r=await fetch(u);if(!r.ok)return [];const d=await r.json();return (d.results||[]).map(x=>normJob(x,'Adzuna'))}
async function arbeitnow(q){const r=await fetch('https://www.arbeitnow.com/api/job-board-api');if(!r.ok)return [];const d=await r.json();const words=q.toLowerCase().split(/\s+/).filter(Boolean);return (d.data||[]).filter(j=>{const hay=`${j.title||''} ${j.description||''} ${j.location||''} ${j.tags||''}`.toLowerCase();return words.some(w=>hay.includes(w))}).slice(0,12).map(x=>normJob(x,'Arbeitnow'))}
async function remotive(q,country){const u=new URL('https://remotive.com/api/remote-jobs');u.searchParams.set('search',q);u.searchParams.set('limit','20');const r=await fetch(u);if(!r.ok)return [];const d=await r.json();const names={PK:'pakistan',IN:'india',AE:'united arab emirates',SA:'saudi arabia',GB:'united kingdom',DE:'germany',CA:'canada',AU:'australia',US:'united states',NL:'netherlands'};const wanted=names[country]||'';return (d.jobs||[]).filter(j=>!wanted||/worldwide|anywhere/i.test(j.candidate_required_location||'')||(j.candidate_required_location||'').toLowerCase().includes(wanted)).slice(0,12).map(x=>normJob(x,'Remotive'))}
async function jooble(env,country,q){if(!env.JOOBLE_API_KEY)return [];const r=await fetch(`https://jooble.org/api/${env.JOOBLE_API_KEY}`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({keywords:q,location:country==='remote'?'remote':country})});if(!r.ok)return [];const d=await r.json();return (d.jobs||[]).slice(0,12).map(x=>normJob(x,'Jooble'))}
async function jsearch(env,country,q){if(!env.JSEARCH_RAPIDAPI_KEY)return [];const host='jsearch.p.rapidapi.com';const u=new URL('https://jsearch.p.rapidapi.com/search');u.searchParams.set('query',`${q} ${country==='remote'?'remote':country}`);u.searchParams.set('page','1');u.searchParams.set('num_pages','1');const r=await fetch(u,{headers:{'X-RapidAPI-Key':env.JSEARCH_RAPIDAPI_KEY,'X-RapidAPI-Host':host}});if(!r.ok)return [];const d=await r.json();return (d.data||[]).slice(0,12).map(x=>normJob(x,'JSearch'))}
function score(job,terms){const hay=`${job.title} ${job.description} ${job.company}`.toLowerCase();let s=0;for(const t of terms){if(hay.includes(t))s+=10}if(job.remote)s+=3;return Math.min(99,Math.max(35,s+55))}

function boardLinks(country,q){const term=encodeURIComponent(q);const common=[{name:'LinkedIn Jobs',url:`https://www.linkedin.com/jobs/search/?keywords=${term}`},{name:'Indeed',url:`https://www.indeed.com/jobs?q=${term}`},{name:'Glassdoor',url:`https://www.glassdoor.com/Job/jobs.htm?sc.keyword=${term}`},{name:'Bayt',url:`https://www.bayt.com/en/international/jobs/?q=${term}`}];const local={PK:[{name:'Rozee.pk',url:`https://www.rozee.pk/job/jsearch/q/${term}`},{name:'Mustakbil',url:`https://www.mustakbil.com/jobs/pakistan/${term}`}],IN:[{name:'Naukri',url:`https://www.naukri.com/${term.replace(/%20/g,'-')}-jobs`}],AE:[{name:'GulfTalent',url:`https://www.gulftalent.com/search?search=${term}`}],GB:[{name:'Reed',url:`https://www.reed.co.uk/jobs?keywords=${term}`}],DE:[{name:'StepStone Germany',url:`https://www.stepstone.de/jobs/${term}`}]}[country]||[];return [...local,...common]}
async function jobs(req,env){const b=await req.json();const country=clean(b.country,20)||'remote';let role=clean(b.role,120);const resume=clean(b.resumeText,30000);if(!resume&&!role)return json({success:false,error:'Provide a CV text or role keywords.'},400);try{if(!role&&resume){const r=await aiText(env,[{role:'system',content:'Extract a concise job-search query from this CV. Return only 5 to 12 keywords or a short role phrase.'},{role:'user',content:resume}]);role=r.answer.replace(/[\n\r]/g,' ').slice(0,120)}const q=role||'software developer';const [a,an,re,j,jr]=await Promise.all([adzuna(env,country,q).catch(()=>[]),arbeitnow(q).catch(()=>[]),remotive(q,country).catch(()=>[]),jooble(env,country,q).catch(()=>[]),jsearch(env,country,q).catch(()=>[])]);let all=[...a,...an,...re,...j,...jr];const terms=q.toLowerCase().split(/\s+/).filter(x=>x.length>2);const seen=new Set();all=all.filter(x=>x.url&&!seen.has(x.url)&&seen.add(x.url)).map(x=>({...x,match:score(x,terms)})).sort((x,y)=>y.match-x.match).slice(0,30);const sources=[...new Set(all.map(x=>x.source))];return json({success:true,jobs:all,query:q,country,sources,boardLinks:boardLinks(country,q),message:all.length?'Matches ranked by keyword fit and source quality.':'No connected source returned matches.'})}catch(e){return json({success:false,error:e.message},502)}}
export default {async fetch(req,env){if(req.method==='OPTIONS')return json({success:true});const url=new URL(req.url);if(url.pathname==='/api/chat'&&req.method==='POST')return chat(req,env);if(url.pathname==='/api/generate'&&req.method==='POST')return generate(req,env);if(url.pathname==='/api/jobs'&&req.method==='POST')return jobs(req,env);if(url.pathname==='/api/health')return json({success:true,service:'Dost AI',ai:!!(env.OPENROUTER_API_KEY||env.AI),jobSources:{adzuna:!!(env.ADZUNA_APP_ID&&env.ADZUNA_APP_KEY),arbeitnow:true,remotive:true,jooble:!!env.JOOBLE_API_KEY,jsearch:!!env.JSEARCH_RAPIDAPI_KEY}});return env.ASSETS?.fetch(req)??new Response('Dost AI',{status:200})}};
